from PIL import Image
from configs.config import SPLIT_RATIO


def split_page(image_path, split_ratio: float | None = None) -> tuple:
    # Input pages are generated by our own pipeline and can exceed Pillow's default safety threshold.
    Image.MAX_IMAGE_PIXELS = None
    ratio = SPLIT_RATIO if split_ratio is None else split_ratio
    with Image.open(image_path) as img:
        w, h = img.size
        mid = int(w * ratio)
        left = img.crop((0, 0, mid, h)).copy()
        right = img.crop((mid, 0, w, h)).copy()
    return left, right


def apply_crop_margins(
    img: Image.Image, crop_rule: dict[str, float | int] | None
) -> Image.Image:
    """Crop margins using top/left/right only (bottom handled in OCR stage)."""
    if not crop_rule:
        return img

    w, h = img.size

    def _as_px(value, total: int) -> int:
        if value is None:
            return 0
        v = float(value)
        if 0.0 <= v < 1.0:
            return int(total * v)
        return max(0, int(v))

    left = _as_px(crop_rule.get("left"), w)
    right = _as_px(crop_rule.get("right"), w)
    top = _as_px(crop_rule.get("top"), h)

    x0 = min(max(0, left), w - 1)
    y0 = min(max(0, top), h - 1)
    x1 = max(x0 + 1, min(w, w - right))
    y1 = h
    return img.crop((x0, y0, x1, y1)).copy()
